# Generated by Django 3.1.1 on 2020-12-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedBasket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
